import Head from 'next/head';
import React from 'react';

const metaData = {
  siteName: 'Disk Golf',
  description: 'Generated by create next app',
};

interface LayoutInterface {
  pageTitle?: string,
  children: React.ReactChild | React.ReactChild[] | React.ReactChildren | React.ReactChildren[]
}

export const Layout = ({ pageTitle = '', children }:LayoutInterface) => (
  <>
    <Head>
      <title>{pageTitle !== '' ? `${pageTitle} | ${metaData.siteName}` : metaData.siteName}</title>
      <meta
        name="description"
        content={metaData.description}
      />
      <link
        rel="icon"
        href="/favicon.ico"
      />
    </Head>
    {children}
  </>
);
