import Head from 'next/head';
import React from 'react';
import { Banner } from './banner';

const metaData = {
  siteName: 'Disk Golf',
  description: 'Generated by create next app',
};

interface LayoutInterface {
  showHeader?: boolean,
  pageTitle?: string,
  children: React.ReactChild | React.ReactChild[] | React.ReactChildren | React.ReactChildren[]
}

const banner = {
  show: true,
  link: 'google.com',
  text: 'Some text here',
  cta: 'Learn More',
};

export const Layout = ({
  pageTitle = '', children, showHeader = true,
}:LayoutInterface) => (
  <>
    <Head>
      <title>{pageTitle !== '' ? `${pageTitle} | ${metaData.siteName}` : metaData.siteName}</title>
      <meta
        name="description"
        content={metaData.description}
      />
      <link
        rel="icon"
        href="/favicon.ico"
      />
    </Head>
    {banner.show && (
    <Banner
      text={banner.text}
      link={banner.link}
      cta={banner.cta}

    />
    )}
    <main>
      {children}
    </main>
  </>
);
